version: '3.8'

services:
  sqlia-app:
    build: .
    container_name: sqlia-backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000" # Ecouté uniquement par l'hôte (pour Nginx VPS)
    environment:
      # On pointe maintenant vers le service docker "ollama"
      - OLLAMA_BASE_URL=http://ollama:11434
      # Configuration Oracle
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - ORACLE_DSN=oracle:1521/FREEPDB1
      - APP_USER=${ORACLE_USER}
    depends_on:
      - oracle
      - ollama

  oracle:
    image: gvenzl/oracle-free:latest-faststart
    container_name: oracle-free
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${ORACLE_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    volumes:
      - ./oracle/oradata:/opt/oracle/oradata
      - ./oracle/init:/container-entrypoint-initdb.d:ro

  ollama:
    image: ollama/ollama:latest
    container_name: sqlia-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  oradata:
  ollama_data:
